apiVersion: v1
kind: Service
metadata:
  name: devops-qr-service
spec:
  type: NodePort
  selector:
    app: devops-qr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007

