name: Deploy to K3s (Self-Hosted Runner)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Fix K3s Permissions for GitHub Actions
        run: |
          sudo chown $USER /etc/rancher/k3s/k3s.yaml
          sudo chmod 644 /etc/rancher/k3s/k3s.yaml
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

      - name: Build Docker Image
        run: |
          docker build -t joelmlsp/devops-qr-app:v1 .
          docker push joelmlsp/devops-qr-app:v1

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get services

